# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.4

# Mod Properties
mod_version=3.6.132-FIX
maven_group=cat.rezelyn
archives_base_name=WatheExtended

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.116.8+1.21.1
wathe_version=1.3.2-1.21.1
harpymodloader_version=1.2.4-h1.3
    noelles_roles_version=1.7.1-h1.3
    stupid_express_version=0.7.1
    starexpress_version=1.3.2
    kinswathe_version=1.6.3
cca_version=6.1.1
    ratatouille_version=1.4.3-1.21.1
yacl_version=3.8.0+1.21.1-fabric
fzzyConfigVersion=0.7.6+1.21
owo_version=0.12.15.4+1.21
voicechat_api_version=2.6.0
voicechat_mod_version=1.21.1-2.6.4
modmenu_version=11.0.3
carpet_version=1.4.147
playercontrol_version=1.0.0
